config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('laboratorio.urls')), #Url base/principal
    path('paciente/', include('pacientes.urls')), #Url pacientes
    path('estudio/', include('estudios.urls')), #Url pacientes
   
]

pacientes/urls.py
from django.urls import path, include

from .views import paciente_nuevo_modal, nuevo_paciente, ver_paciente, pacientes, \
    editar_paciente,eliminar_paciente, confirmar_eliminacion_paciente, ajax_get_view, ver_todos_los_pacientes, ver_todos_filtro, not_fund

app_name = 'pacientes'

urlpatterns = [
    path('', pacientes, name='pacientes_' ),
    path('nuevo/', nuevo_paciente, name='nuevo_paciente' ),
    path('nuevo_modal/', paciente_nuevo_modal, name='nuevo_paciente_modal' ),
    path('ver/<pk>', ver_paciente.as_view(), name='ver_paciente' ),
    path('editar/<pk>/', editar_paciente, name='editar_paciente' ),
    path('eliminar/<pk>/', eliminar_paciente, name='eliminar_paciente' ),
    path('confirmar_eliminacion/', confirmar_eliminacion_paciente, name='confirm_eliminacion_paciente' ),
    path('ver_todos/', ver_todos_los_pacientes.as_view(), name='ver_todos_los_pacientes' ),
    path('ver_todos_filtro/', ver_todos_filtro, name='ver_todos_filtro' ),
    path('buscar2/', ajax_get_view, name='buscar_paciente_2' ),
    path('404/', not_fund, name='404' ),
]

pacientes/models.py
from django.db import models


# Create your models here.
class Paciente( models.Model ):
    nombre = models.CharField( max_length=200 )
    apellido = models.CharField( max_length=200 )
    dni = models.CharField( max_length= 10, primary_key=True )
    celular = models.CharField( max_length=200 )
    direccion = models.CharField( max_length= 200 )
    fecha_registro = models.DateTimeField( auto_now_add=True)

    
    SEX_CHOICE = (
        ('F', 'Femenino',),
        ('M', 'Masculino',),
        ('I', 'Indefinido',),
    )

    sexo = models.CharField(
        max_length= 1,
        choices=SEX_CHOICE,
    )

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = 'Paciente'
        verbose_name_plural = 'Pacientes'

pacientes/forms.py
from django import forms

from .models import Paciente

class formulario_nuevo_paciente_principal( forms.ModelForm ):
    class Meta:
        model = Paciente
        fields = ('nombre', 'apellido', 'dni', 'celular')

        labels = {}
        for i in fields:
            labels[i] = i.capitalize()

        widgets = {
            'nombre': forms.TextInput(
                            attrs={
                                'class':'form-control',
                                'placeholder':'Nombre',

                            }
                        ),

            'apellido': forms.TextInput( 
                            attrs={
                                'class':'form-control',
                                'placeholder':'Apellido',
                            }
                        ),

            'dni': forms.TextInput( 
                            attrs={
                                'class':'form-control',
                                'placeholder':'DNI',
                                'max':10,
                                'min':10,
                                'type':'number',
                                'onChange':'buscarPaciente( "en_nuevo_paciente" )',
                            }
                        ),

            'celular': forms.TextInput( 
                            attrs={
                                'class':'form-control',
                                'placeholder':'Celular',
                                'type':'number',
                            }
                        ),
            
            'direccion': forms.TextInput( 
                            attrs={
                                'class':'form-control',
                                'placeholder':'Direccion',
                            }
                        ),
            
            'sexo': forms.Select( 
                            attrs={
                                'class':'form-control',
                            }
                        )
        }


class formulario_nuevo_paciente_modal( forms.ModelForm ):
    class Meta:
        model = Paciente
        fields = ('nombre', 'apellido', 'dni', 'celular')

        widgets = {
            'nombre': forms.TextInput(
                            attrs={
                                'class':'form-control',
                                'placeholder':'Nombre',

                            }
                        ),

            'apellido': forms.TextInput( 
                            attrs={
                                'class':'form-control',
                                'placeholder':'Apellido',
                            }
                        ),

            'dni': forms.TextInput( 
                            attrs={
                                'class':'form-control',
                                'placeholder':'DNI',
                                'max':'10',
                                'min':'10',
                                'type':'number',
                                'onChange':'buscarPaciente2()',
                            }
                        ),

            'celular': forms.TextInput( 
                            attrs={
                                'class':'form-control',
                                'placeholder':'Celular',
                                'type':'number',
                            }
                        ),
            
        }
        
            

pacientes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse, Http404, HttpResponse
import json
import pandas as pd
from django.utils.encoding import uri_to_iri
from django.urls import reverse


from django.views.generic import CreateView, DetailView, UpdateView, ListView, DeleteView

from .forms import formulario_nuevo_paciente_principal, formulario_nuevo_paciente_modal
from .models import Paciente
from estudios.models import Estudio_Hemograma, Estudio_Embarazada, Estudio_Hepatograma, Estudio_Orina, Estudio_Urocultivo, \
        Estudio_Proteinograma, Estudio_Quimica, Estudio_Cultivo, Estudio_Parasitologico, Estudio_General

# Create your views here.

def nuevo_paciente( request ):
    if request.method == 'POST':
        form = formulario_nuevo_paciente_principal(request.POST)

        if form.is_valid():
            form.save()
            data = {
                'valid':form.is_valid()
            }

            return JsonResponse(data)
    else:
        form = formulario_nuevo_paciente_principal

    return render( request, 'nuevo_paciente.html', {'form':form} )

def paciente_nuevo_modal( request ):
    if request.method == 'POST':
        formulario = formulario_nuevo_paciente_modal(request.POST)

        if formulario.is_valid():
            formulario.save()
            data = {
                'valid':formulario.is_valid()
            }

            return JsonResponse(data)
    else:
        formulario = formulario_nuevo_paciente_modal

    return render( request, 'formularios/formulario_nuevo_paciente.html', {'formulario':formulario} )

def not_fund( request ):
    return render( request, '404.html')

class ver_paciente( DetailView ):
    model = Paciente
    context_object_name = 'paciente'
    template_name = 'ver_paciente.html'

    def get(self, request, *args, **kwargs):
        try:
            return super().get(request, *args, **kwargs)
        except Http404:
            return redirect(reverse('pacientes:404'))



    def get_context_data( self, **kwargs ):
        context = super( ver_paciente, self ).get_context_data(**kwargs )

        try:
            dni=Paciente
        except dni.DoesNotExist:
            raise Http404("Book does not exist")

        todos_los_estudios = (
                Estudio_Hemograma.objects.filter( paciente_id = self.object.dni ),
                Estudio_Embarazada.objects.filter( paciente_id = self.object.dni ),
                Estudio_Hepatograma.objects.filter( paciente_id = self.object.dni ),
                Estudio_Orina.objects.filter( paciente_id = self.object.dni ),
                Estudio_Urocultivo.objects.filter( paciente_id = self.object.dni ),
                Estudio_Proteinograma.objects.filter( paciente_id = self.object.dni ),
                Estudio_Quimica.objects.filter( paciente_id = self.object.dni ),
                Estudio_Cultivo.objects.filter( paciente_id = self.object.dni ),
                Estudio_Parasitologico.objects.filter( paciente_id = self.object.dni ),
                Estudio_General.objects.filter( paciente_id = self.object.dni )
            )

        estudios_del_paciente = ()

        for estudios_realizados in todos_los_estudios:
            
            if estudios_realizados.exists():
                estudios_del_paciente += ( tuple(estudios_realizados) )

        def estudio_ver( valor ):
            
            categorias = []
            for estudio in estudios_del_paciente:

                if valor == 'objeto':
                    categorias.append( estudio )
                    
                if valor == 'categoria':
                    categorias.append( estudio.categoria )

                if valor == 'fecha':
                    categorias.append( estudio.fecha_estudio )
                
            return categorias
        
        def mostrar_estudios_recientes( ):
            indices = []


            for i in range(len(estudios_del_paciente)):
                indices.append( str(i) )

            estudios = {
                'obj': estudio_ver('objeto'),
                'categoria': estudio_ver('categoria'),
                'fecha': estudio_ver('fecha'),

            }

            data_frame = pd.DataFrame( data=estudios, index=indices )
            data_frame['fecha'] =pd.to_datetime(data_frame['fecha'])

            data_frame = data_frame.sort_values( by='fecha', ascending=False)

            estudios_ordenados_recientes = data_frame['obj'].tolist()

            
            return estudios_ordenados_recientes
            

        context['estudios_del_paciente'] = mostrar_estudios_recientes()
               

        return context

def pacientes( request ):
    return render( request, 'pacientes.html')
'''
class editar_paciente( UpdateView ):
    model = Paciente
    form_class = formulario_nuevo_paciente_principal
    template_name = 'editar_paciente.html'
    success_url = '/'
'''
def editar_paciente( request, pk ):
    paciente = get_object_or_404(Paciente, pk = pk )


    if request.method == 'POST':
        form = formulario_nuevo_paciente_principal( request.POST or None, instance=paciente )
        if form.is_valid():
            form.save()
            data = {
                'valid':form.is_valid()
            }

            return JsonResponse(data)

    else:
        form = formulario_nuevo_paciente_principal( instance = paciente )
    
    contexto = {'form':form, 'dni':pk}

    return render( request, 'editar_paciente.html', contexto )
    
'''
class eliminar_paciente( DeleteView ):
    model = Paciente
    context_object_name = 'paciente'
    template_name = 'eliminar_paciente.html'
    success_url = '/'
'''

def eliminar_paciente( request, pk ):
    

    contexto = {'dni':pk}

    #return JsonResponse(data)
    return render( request, 'eliminar_paciente.html', contexto)

def confirmar_eliminacion_paciente( request ):
    post_data = json.loads( request.body.decode("utf-8") )
    dni_a_eliminar = post_data['elemento']
    
    
    
    paciente = get_object_or_404( Paciente, dni = dni_a_eliminar )

    paciente.delete()
    
    data = {
        'valid':True
    }

    return JsonResponse(data)

def ver_todos_filtro( request ):
    return render( request, 'menu_todos_los_pacientes.html')

class ver_todos_los_pacientes( ListView ):
    model = Paciente
    context_object_name = 'pacientes'
    template_name = 'todos_los_pacientes.html'
    paginate_by = 20

    def get_ordering( self ):
        ordenar_por = self.request.GET.get('ordering')
        ordering = self.request.GET.get('ordering', '-fecha_registro')

        if ordenar_por == 'fecha-registro':
            ordering = self.request.GET.get('ordering', '-fecha_registro')
        if ordenar_por == 'nombre':
            ordering = self.request.GET.get('ordering', 'nombre')
        if ordenar_por == 'apellido':
            ordering = self.request.GET.get('ordering', '-apellido')
        

        return ordering

    def get_context_data( self, *args, **kwargs):
        context = super( ver_todos_los_pacientes, self ).get_context_data( *args, **kwargs )

        #Solucion para mantener el filtrado durante todo el proceso de paginación
        # https://stackoverflow.com/questions/59972694/django-pagination-maintaining-filter-and-order-by
        
    
        context['order'] = self.get_ordering()
        return context

def ajax_get_view(request):
    post_data = json.loads( request.body.decode("utf-8") )
    dni_paciente = post_data['elemento']
    
    chequear_exitencia =  Paciente.objects.filter( dni = dni_paciente ).exists()

    if chequear_exitencia:
        paciente = Paciente.objects.get( dni = dni_paciente )
        nombre_completo_paciente = paciente.nombre + ' ' + paciente.apellido

        data = {
            'dni':chequear_exitencia,
            'paciente_nombre':nombre_completo_paciente
            
        }
    else:
        data = {
            'dni':chequear_exitencia,
            
        }


    return JsonResponse(data)
    
def obtener_dni( dni ):
    return dni

    

pacientes/templates/busqueda.html
{% if paciente %}

<div class="col-md-12 mt-3 m-0 ">
    <div class="alert alert-success" role="alert">
        ¡Se encontraron resultados!
    </div>
    <div class="card" style="width: 18rem;">
        <div class="card-body">
        <center>
          <h5 class="card-title">{{paciente.nombre}} {{paciente.apellido}}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{paciente.dni}}</h6>
          <button onclick="cambiarContenedor( 'ver_paciente' , '{{paciente.dni}}' )" class="btn btn-primary ">Ver</button>
          <a href="{% url 'pacientes:editar_paciente' paciente.dni %}" class="btn btn-warning ">Editar</a>
          <a href="{% url 'pacientes:eliminar_paciente' paciente.dni %}" class="btn btn-danger ">Eliminar</a>
        </center>
        </div>
    </div>
</div>
{% else %}
<div class="col-md-12 mt-3 m-0 ">
    <div class="row justify-content-center text-center">
        <h1>El dni <span class="text-primary">{{dato}}</span> no existe <i class="fas fa-sad-tear"></i></h1>
        
    </div>

</div>

{% endif %}

pacientes/templates/editar_paciente.html
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="modal_titulo">Editar perfil del paciente</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
      <div class="row justify-content-center ml-2 mr-2">
        <form action="" method="POST" class="w-100" id="form_editar_paciente">
            {% csrf_token %}
            {{form}}
        </form>
        <button id="btn-crear" type="button" class="btn btn-primary w-100 mt-3" onclick="enviar_formulario('paciente','edicion','form_editar_paciente', '', '{{dni}}')">Guardar</button>

      </div>
    </div>
  </div>
</div>
<script>
  dni_editar_paciente = document.getElementById('id_dni');
  dni_editar_paciente.setAttribute('readonly', '');

  

</script>

pacientes/templates/eliminar_paciente.html
<div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal_titulo">Eliminar</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
      </div>
      <div class="modal-body">
            
        <h6>Esta seguro que quiere eliminar al paciente ?</h6>
            
        <button id="btn-crear" type="button" class="btn btn-danger float-right mt-3" onclick="enviar_formulario('paciente','eliminacion','', '', '{{dni}}')">Confirmar</button>

      </div>
    </div>
  </div>

pacientes/templates/menu_todos_los_pacientes.html
<div class="col-md-12 p-3 table-responsive">
    <div class="row">
      <div class="input-group mb-3">
        <div class="input-group-prepend">
          <label class="input-group-text cont-ordenar_por bg-primary" for="inputGroupSelect01">Ordenar por</label>
        </div>
        <select class="custom-select cont-select" id="select"  onchange="select()">
          <option id="ordenar_fecha" value="ordenar_fecha">Ultimos registrados</option>
          <option id="ordenar_nombre" value="ordenar_nombre"  >Nombre ( A a la Z )</option>
          <option id="ordenar_apellido" value="ordenar_apellido" >Apellido ( A a la Z )</option>
        </select>
      </div>
    </div>
      <div class="row justify-content-center" id="mostrar_tabla">
        
      </div>
        
      
  </div>
  {% block extrajs %}
  <script>    
    
   
      
    url = '../../paciente/ver_todos/';
    $('#mostrar_tabla').load( url )
      

    function select(){  
        let select = document.getElementById('select').value;
        let option_actual = document.getElementById(select);
        
       
        if( option_anterior != null ){
            option_anterior.removeAttribute('selected', '');
        }
        option_actual.setAttribute('selected', '')
        option_anterior = option_actual;
        
        cambiarContenedor( select )
        
    }
    
  </script>
  {% endblock %}

pacientes/templates/nuevo_paciente.html
<div class="col p-3">
  <div class="row justify-content-center mb-3">
    <h4>Nuevo paciente</h4>
  </div>
  <div class="row justify-content-center">
    <form action="" method="POST" id="form_crear_paciente">
      {% csrf_token %}
      <div class="input-group mb-3">
  
        {{form.nombre}}
        {{form.apellido}}
      </div>
      <div class="form-group mb-3" id="input-dni">
        {{form.dni}}
        <small id="dni_small" class="form-text text-muted" style="display: none;"></small>
      </div>
      <div class="input-group mb-3">

        {{form.celular}}
      </div>


    </form>
  </div>
  <div class="row justify-content-center">
    <button id="btn-enviar" type="button" class="btn btn-success w-50" onclick="enviar_formulario('paciente','creacion','form_crear_paciente')">Guardar</button>

  </div>
</div>

pacientes/templates/pacientes.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-md-12 pt-3">
    
    <div class="row align-items-center" >
        <div class="col-auto text-center">
            <a href='#' id="crear_paciente" onclick='cambiarContenedor( "nuevo_paciente" )' class="btn btn-paciente btn-success">
                <i class="fas fa-plus" ></i>
                
            </a>
        </div>
        <div class="col-auto">
            <a href='#' id="ver_pacientes"  onclick="cambiarContenedor( 'ver_pacientes' )" class="btn btn-paciente btn-primary">
                <i class="far fa-eye"></i>
            </a>
        </div>
        <div class="col">
            
                <div class="input-group w-100">
                    <input type="number" class="form-control" id="dni" placeholder="Buscar por dni" style="border-top-left-radius: 30px;border-bottom-left-radius: 30px;">
                    <div class="input-group-append">
                   
                        <button id="buscar" onclick="buscarPaciente( 'en_buscar_paciente' )" class="btn btn-search btn-primary"><i class="fas fa-search"></i></button>
                    </div>
                  </div>
            
        </div>
    </div>
    <div class="row p-3" id="contenedor_dinamico">
        <div  class="col detalle" >
            <h1>Pacientes</h1>
            
        </div>
    </div>
</div>


{% endblock %}
{% block extrajs %}

<script src="{% static 'js/buscar_paciente.js' %}"></script>
<script src="{% static 'js/enviar_json.js' %}"></script>
{% endblock %}

pacientes/templates/todos_los_pacientes.html
<div class="col-md-6">     
  <div class="row">
    <table class="table table-sm table-striped ">
           <thead class="thead-dark">
             <tr>
               <th scope="col">Nombre</th>
               <th scope="col">Dni</th>
             </tr>
           </thead>
           <tbody> <!---TBODY ES EL CUERPO DE LA TABLA-->
   
               {% for i in pacientes %} <!---BUCLE PARA i = 0, hasta el numero de pacientes que contenga( ej: 5 )-->
               <tr><!---TR ES la fila que tiene cada paciente-->
                   <th scope="row" ><a id="ver" class="btn_ver" type="button" onclick="cambiarContenedor( 'ver_paciente', '{{i.dni}}' )">{{i.nombre}} {{i.apellido}}</a></th><!---Nombre y apellido-->
                   <th scope="row">{{i.dni}}</th><!---Dni-->
               </tr>
               {% endfor %} </th><!---Fin para-->
             
           </tbody>
         </table>
   </div>

   <div class="row justify-content-center mb-2">
    
     {% if page_obj.has_previous %}
     <!--<span><button onclick="cambio('?ordering={{order}}&page=1')">Primera</button></span>-->
     <button class="btn btn-primary btn-paciente" type="button" onclick="cambio('?ordering={{order}}&page={{ page_obj.previous_page_number }}')"><i class="fas fa-caret-left"></i></button>
     {% endif %}
    
    <div class="col-auto">
      <span>{{ page_obj.number }} de {{ page_obj.paginator.num_pages }}</span>
    </div>

     {% if page_obj.has_next %}
     <button class="btn btn-primary btn-paciente" type="button" onclick="cambio('?ordering={{order}}&page={{ page_obj.next_page_number }}')" ><i class="fas fa-caret-right"></i></button>
     <!--<span><button onclick="cambio('?ordering=-fecha_registro&page={{ page_obj.paginator.num_pages }}')" >Ultima</button></span>-->
     {% endif %}
    </div>
  </div>
   

  

</div>



    <script>
      

      tippy('#ver', {
          content: 'Ver registro',
          placement: 'left',
      });

      tippy('#copiar_dni', {
          content: 'Copiar DNI',
          placement: 'right',
      });

      function cambio( valor ){
        url = '../../paciente/ver_todos/'+valor;
        $('#mostrar_tabla').load( url )
      }
    </script>

pacientes/templates/ver_paciente.html
{% load static %}
{% block content %}

<div class="col-md-3 p-3 border-right">
    <div class="row justify-content-center">
            <h4 id="name_paciente" >{{paciente.nombre}} {{paciente.apellido}}</h4>  
    </div>

    <div class="row justify-content-center">
        <footer class="blockquote-footer">Dni: <cite title="Source Title" class="text-primary" id="dni_copy">{{paciente.dni}}</cite></footer>
    </div>
    <div class="row justify-content-center">
        <footer class="blockquote-footer">Celular: <cite title="Source Title" class="text-primary"><a href="tel:{{paciente.celular}}"> {{paciente.celular}}</a></cite></footer>
    </div>
    <div class="row justify-content-center">
        {% if paciente.direccion %}
        {% else %}
        <footer class="blockquote-footer">Direccion: <cite title="Source Title" class="text-muted">Sin registrar</cite></footer>
        {% endif %}
    </div>
    <div class="row justify-content-center">
        <footer class="blockquote-footer">Registrado el: <cite title="Source Title" class="text-primary"> {{paciente.fecha_registro.day}} / {{paciente.fecha_registro.month}} / {{paciente.fecha_registro.year}}</cite></footer>
    </div>
    <div class="row justify-content-center mt-3">
        <div class="col-auto">
            <a onclick="cambiarContenedor( 'editar_paciente', '{{paciente.dni}}')" id="edit" class="btn btn-paciente btn-warning">
                <i class="far fa-edit"></i>
            </a>
        </div>
        <div class="col-auto">
            <a  onclick="cambiarContenedor( 'eliminar_paciente', '{{paciente.dni}}')" id="delete"  class="btn btn-paciente btn-danger" >
                <i class="far fa-trash-alt"></i>
            </a>
        </div>
    </div>

               

       
</div>
<div class="col-md-9 p-3">
    {% if estudios_del_paciente %}

    

    <div class="row">
    {% for ver in estudios_del_paciente %}
        <div class="col-md-4 p-2" id="contenedor_estudios">
            <div class="row justify-content-center">
                <div class="col-10 text-dark border rounded p-2">
                    <small>Análisis</small>
                    {% if ver.categoria is 0 %}
                    <h6 class="text-light"><span class="pl-1  bg-0 pr-4 rounded-right">{{ver}} <i class="fas fa-poll-h"></i></span></h6>
                    {% elif ver.categoria is 1 %}
                    <h6 class="text-light"><span class="pl-1  bg-1 pr-4 rounded-right">{{ver}} <i class="fas fa-poll-h"></i></span></h6>
                    {% elif ver.categoria is 2 %}
                    <h6 class="text-light"><span class="pl-1  bg-2 pr-4 rounded-right">{{ver}} <i class="fas fa-poll-h"></i></span></h6>
                    {% elif ver.categoria is 3 %}
                    <h6 class="text-light"><span class="pl-1  bg-3 pr-4 rounded-right">{{ver}} <i class="fas fa-poll-h"></i></span></h6>
                    {% elif ver.categoria is 4 %}
                    <h6 class="text-light"><span class="pl-1  bg-4 pr-4 rounded-right">{{ver}} <i class="fas fa-poll-h"></i></span></h6>
                    {% elif ver.categoria is 5 %}
                    <h6 class="text-light"><span class="pl-1  bg-5 pr-4 rounded-right">{{ver}} <i class="fas fa-poll-h"></i></span></h6>
                    {% elif ver.categoria is 6 %}
                    <h6 class="text-light"><span class="pl-1  bg-6 pr-4 rounded-right">{{ver}} <i class="fas fa-poll-h"></i></span></h6>
                    {% elif ver.categoria is 7 %}
                    <h6 class="text-light"><span class="pl-1  bg-7 pr-4 rounded-right">{{ver}} <i class="fas fa-poll-h"></i></span></h6>
                    {% elif ver.categoria is 8 %}
                    <h6 class="text-light"><span class="pl-1  bg-8 pr-4 rounded-right">{{ver}} <i class="fas fa-poll-h"></i></span></h6>
                    {% elif ver.categoria is 9 %}
                    <h6 class="text-light"><span class="pl-1  bg-9 pr-4 rounded-right">{{ver}} <i class="fas fa-poll-h"></i></span></h6>

                    {% endif %}
                    <hr>
                    <footer class="blockquote-footer text-muted">Hecho el: <cite title="Source Title" class="border border-primary text-muted rounded pl-2 pr-2">{{ver.fecha_estudio.day}} / {{ver.fecha_estudio.month}} / {{ver.fecha_estudio.year}}</cite></footer>
                    <hr>
                    <div class="row justify-content-center">
                        <div class="col-auto"><button id="ver_estudio_tippy" onclick="ver_estudio('{{ver.id}}', '{{ver.categoria}}', '{{ver.paciente_id}}')"  class="btn btn-paciente btn-primary mb-2"><i class="far fa-eye"></i></button>
                        </div>
                        <div class="col-auto"><button id="editar_estudio" onclick="editar_estudio('{{ver.id}}', '{{ver.categoria}}' )"  class="btn btn-paciente btn-warning mb-2"><i class="far fa-edit"></i></button>
                        </div>
                        <div class="col-auto"><button id="eliminar_estudio" onclick="eliminar_estudio('{{ver.id}}', '{{ver.categoria}}' )"  class="btn btn-paciente btn-danger mb-2"><i class="far fa-trash-alt"></i></button>
                        </div>
                    </div>
                
                </div>
            </div>
        </div>
    {% endfor %}
    </div>


{% else %}
    <h5 class="text-center text-muted">Sin estudios</h5>
{% endif %}

</div>
{% block extrajs %}

<script>
    copy_dni = document.querySelector('#dni_copy').innerText;
    name_paciente = document.querySelector('#name_paciente').innerText;

    mostrar_texto = `${copy_dni} - ${name_paciente}` 
    dom_mostrar_dni.innerText = mostrar_texto;
    localStorage.setItem( 'dni_copy', mostrar_texto );

    tippy('#edit', {
        content: 'Editar paciente',
        placement: 'bottom',
    });
    
     tippy('#delete', {
        content: 'Eliminar paciente',
        placement: 'bottom',
    });

    tippy('#ver_estudio_tippy', {
        content: 'Ver estudio',
        placement: 'bottom',
    });

    tippy('#editar_estudio', {
        content: 'Editar estudio',
        placement: 'bottom',
    });

    tippy('#eliminar_estudio', {
        content: 'Eliminar estudio',
        placement: 'bottom',
    });

    function ver_estudio( id, categoria, paciente_id ){
        let url = `../../estudio/ver/${id}/${categoria}/${paciente_id}/`

        $('#ver_estudio').load( url , function(){
            $(this).modal('show');
                    
        })
    }

    function editar_estudio( id, categoria ){
        let url = `../../estudio/editar/${id}/${categoria}/`

        $('#modal_editar_estudio').load( url , function(){
            $(this).modal('show');
                    
        })
    }

    function eliminar_estudio( id, categoria ){
        let url = `../../estudio/eliminar/${id}/${categoria}/`

        $('#modal_eliminar_estudio').load( url , function(){
            $(this).modal('show');
                    
        })
    }



    

</script>
<script src="{% static 'js/jspdf.min.js' %}"></script>
<script src="{% static 'js/jspdf.plugin.autotable.js' %}"></script>


{% endblock %}

<!-- Modal -->
    <div class="modal fade " id="ver_estudio" role="dialog" ></div>
    <div class="modal fade" id="modal_editar" ></div>
    <div class="modal fade" id="modal_eliminar"></div>
    <div class="modal fade" id="modal_editar_estudio"></div>
    <div class="modal fade" id="modal_eliminar_estudio"></div>

{% endblock %}