config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('laboratorio.urls')), #Url base/principal
    path('paciente/', include('pacientes.urls')), #Url pacientes
    path('estudio/', include('estudios.urls')), #Url pacientes
   
]

estudios/urls.py
from django.urls import path, include

from .views import estudios_page, \
                nueva_caratula, \
                nuevo_estudio, \
                ver_estudio, \
                editar_estudio, \
                eliminar_estudio, \
                confirm_eliminacion_estudio

app_name = 'estudios'
urlpatterns = [
    path('', estudios_page, name='estudios_' ),


    path('nuevo_estudio/<categoria>/', nuevo_estudio, name='nuevo_estudio' ),
    path('nueva_caratula/', nueva_caratula, name='nueva_caratula' ),
    path('ver/<id_estudio>/<categoria>/<paciente_id>/', ver_estudio, name='ver_estudio' ),
    path('editar/<id_estudio>/<categoria>/', editar_estudio, name='editar_estudio' ),
    path('eliminar/<id_estudio>/<categoria>/', eliminar_estudio, name='eliminar_estudio' ),
    path('confirmar_eliminacion_estudio/', confirm_eliminacion_estudio, name='confirm_eliminar_estudio' ),

]

laboratorio/urls.py
from django.urls import path, include

from .views import pagina_bienvenida, pagina_principal

app_name = 'laboratorio'

urlpatterns = [
    path('bienvenida/', pagina_bienvenida, name='pag_bienvenida' ), #Pagina de bienvenida
    
    path('', pagina_principal, name='pag_principal' ), #Pagina principal INDEX
]

pacientes/urls.py
from django.urls import path, include

from .views import paciente_nuevo_modal, nuevo_paciente, ver_paciente, pacientes, \
    editar_paciente,eliminar_paciente, confirmar_eliminacion_paciente, ajax_get_view, ver_todos_los_pacientes, ver_todos_filtro, not_fund

app_name = 'pacientes'

urlpatterns = [
    path('', pacientes, name='pacientes_' ),
    path('nuevo/', nuevo_paciente, name='nuevo_paciente' ),
    path('nuevo_modal/', paciente_nuevo_modal, name='nuevo_paciente_modal' ),
    path('ver/<pk>', ver_paciente.as_view(), name='ver_paciente' ),
    path('editar/<pk>/', editar_paciente, name='editar_paciente' ),
    path('eliminar/<pk>/', eliminar_paciente, name='eliminar_paciente' ),
    path('confirmar_eliminacion/', confirmar_eliminacion_paciente, name='confirm_eliminacion_paciente' ),
    path('ver_todos/', ver_todos_los_pacientes.as_view(), name='ver_todos_los_pacientes' ),
    path('ver_todos_filtro/', ver_todos_filtro, name='ver_todos_filtro' ),
    path('buscar2/', ajax_get_view, name='buscar_paciente_2' ),
    path('404/', not_fund, name='404' ),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}{% endblock %}

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
</head>
<body>
    <div class="container" style="height: 100vh;">
        <div class="row fixed-bottom justify-content-center" >
            <div id="alerta" class="alert alert-success w-50" role="alert" style="display: none;">
                This is a success alert with <a href="#" class="alert-link">an example link</a>. Give it a click if you like.
              </div>
        </div>
        <div class="row pb-3 pt-2 text-center">
           

            {% include 'header.html' %}
        </div>
        <div class="row bg-light p-3 contenedor" id="contenedor_base">
            
      
                {% block content %}{% endblock %}
            
        </div>

        
        <footer class="row justify-content-center text-muted">
            
                <!-- Flexbox container for aligning the toasts -->

            
                <div class="col-3 text-left">Programing by <i class="far fa-copyright"></i>Ivan Cruz - 2021</div>
                <div  class="col-6 text-center"><h6 class="text-dark">Paciente seleccionado: <span class="text-success" id="mostrar_dni"></span></h6></div>
                <div class="col-3 text-right">v1.0</div>
            
        </footer>
        
        

        
    </div>
        
    
    
   
    <script src="{% static 'js/jquery-3.6.0.js' %}" ></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/tippy-bundle.umd.js' %}"></script>
    <script src="{% static 'js/cambiar_contenedor.js' %}"></script>
    <script src="{% static 'js/copiar_dni.js' %}"></script>

    {% block extrajs %}{% endblock %}
    <script>
        $('.toast').toast('show')
    </script>
</body>
</html>

templates/footer.html
<footer class="bg-primary mt-5 w-100">
    Footer
</footer>

templates/header.html
    <div class="col">
      <a href="{% url 'pacientes:pacientes_' %}" type="button" class="btn btn-privado btn-primary"><i class="far fa-address-card"></i> Pacientes</a>
    </div>
    <div class="col">
      <a href="{% url 'laboratorio:pag_principal' %}" type="button" class="btn btn-privado btn-outline-primary"><i class="fas fa-home"></i> Inicio</a>
    </div>
    <div class="col">
      <a href="{% url 'estudios:estudios_' %}" type="button" class="btn btn-privado btn-primary"><i class="fas fa-notes-medical"></i> Analisis</a>
    </div>